production:
  url: <%= ENV['ETHEREUM_URL'] %>
  contract_address: "<%= ENV['ETHEREUM_CONTRACT_ADDRESS'].to_s %>"
  oracle_address: "<%= ENV['ETHEREUM_ORACLE_ADDRESS'].to_s %>"
  realitio_contract_address: "<%= ENV['ETHEREUM_REALITIO_ERC20_CONTRACT_ADDRESS'].to_s %>"

staging:
  url: <%= ENV['ETHEREUM_URL'] %>
  contract_address: "<%= ENV['ETHEREUM_CONTRACT_ADDRESS'].to_s %>"
  oracle_address: "<%= ENV['ETHEREUM_ORACLE_ADDRESS'].to_s %>"
  realitio_contract_address: "<%= ENV['ETHEREUM_REALITIO_ERC20_CONTRACT_ADDRESS'].to_s %>"

development:
  # local testnet
  # url: 'http://localhost:8545'
  # contract_address: '0x49de73CaB6e369f1F97Def0b95b558cd77c5d6a2'
  # oracle_address: '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1'
  # oracle_private_key: '4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d' # DO NOT USE THIS IN PRODUCTION

  # staging testnet
  url: <%= ENV['ETHEREUM_URL'] %>
  contract_address: "<%= ENV['ETHEREUM_CONTRACT_ADDRESS'].to_s %>"
  oracle_address: "<%= ENV['ETHEREUM_ORACLE_ADDRESS'].to_s %>"
  oracle_private_key: "<%= ENV['ETHEREUM_ORACLE_PRIVATE_KEY'].to_s %>" # DO NOT USE THIS IN PRODUCTION
  realitio_contract_address: "<%= ENV['ETHEREUM_REALITIO_ERC20_CONTRACT_ADDRESS'].to_s %>"
  erc20_contract_address: "<%= ENV['ETHEREUM_ERC20_CONTRACT_ADDRESS'].to_s %>"
