default: &default
  <% ENV["ETHEREUM_NETWORK_IDS"].to_s.split(',') do |network_id| %>
    network_<%= network_id %>:
      rpc_api_url: <%= ENV["ETHEREUM_NETWORK_#{network_id}_RPC_API_URL"] || ENV["ETHEREUM_NETWORK_#{network_id}_BEPRO_API_URL"] %>
      rpc_wss_url: <%= ENV["ETHEREUM_NETWORK_#{network_id}_RPC_WSS_URL"] %>
      prediction_market_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_PREDICTION_MARKET_CONTRACT_ADDRESS"].to_s %>"
      realitio_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_REALITIO_ERC20_CONTRACT_ADDRESS"].to_s %>"
      achievements_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ACHIEVEMENTS_CONTRACT_ADDRESS"].to_s %>"
      voting_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_VOTING_CONTRACT_ADDRESS"].to_s %>"
      erc20_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ERC20_CONTRACT_ADDRESS"].to_s %>"
      arbitration_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ARBITRATION_CONTRACT_ADDRESS"].to_s %>"
      arbitration_proxy_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ARBITRATION_PROXY_CONTRACT_ADDRESS"].to_s %>"
      arbitration_network_id: <%= ENV["ETHEREUM_NETWORK_#{network_id}_ARBITRATION_NETWORK_ID"].to_s %>
      image_url: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_IMAGE_URL"].to_s %>"
      burn_from_block: <%= ENV["ETHEREUM_NETWORK_#{network_id}_BURN_FROM_BLOCK"].to_i %>
  <% end %>
  <% ENV["STATS_NETWORK_IDS"].to_s.split(',') do |network_id| %>
    stats_network_<%= network_id %>:
      rpc_api_url: <%= ENV["STATS_NETWORK_#{network_id}_RPC_API_URL"] || ENV["STATS_NETWORK_#{network_id}_BEPRO_API_URL"] %>
      rpc_wss_url: <%= ENV["STATS_NETWORK_#{network_id}_RPC_WSS_URL"] %>
      prediction_market_contract_address: "<%= ENV["STATS_NETWORK_#{network_id}_PREDICTION_MARKET_CONTRACT_ADDRESS"].to_s %>"
      realitio_contract_address: "<%= ENV["STATS_NETWORK_#{network_id}_REALITIO_ERC20_CONTRACT_ADDRESS"].to_s %>"
  <% end %>
    market_list_url: <%= ENV['ETHEREUM_MARKET_LIST_URL'] %>
    network_ids: <%=
      ENV["ETHEREUM_NETWORK_IDS"].to_s.split(',').select do |network_id|
        ENV["ETHEREUM_NETWORK_#{network_id}_DISABLED"].to_s != 'true'
      end
    %>
    fantasy_enabled: <%= ENV["ETHEREUM_FANTASY_ENABLED"] == 'true' %>
    stats_network_ids: <%= ENV["STATS_NETWORK_IDS"].to_s.split(',') %>
    cache_ttl_seconds: <%= ENV["ETHEREUM_CACHE_TTL"] %>
    voting_delta: <%= ENV["ETHEREUM_VOTING_DELTA"] || 3 %>
    blacklist: <%= ENV["ETHEREUM_BLACKLIST"].to_s.split(',') %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
