default: &default
  <% ENV["ETHEREUM_NETWORK_IDS"].to_s.split(',') do |network_id| %>
    network_<%= network_id %>:
      bepro_api_url: <%= ENV["ETHEREUM_NETWORK_#{network_id}_BEPRO_API_URL"] %>
      bepro_api_public_key: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_BEPRO_API_PUBLIC_KEY"] %>"
      admin_private_key: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ADMIN_PRIVATE_KEY"].to_s %>"
      prediction_market_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_PREDICTION_MARKET_CONTRACT_ADDRESS"].to_s %>"
      prediction_market_manager_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_PREDICTION_MARKET_MANAGER_CONTRACT_ADDRESS"].to_s %>"
      prediction_market_controller_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_PREDICTION_MARKET_CONTROLLER_CONTRACT_ADDRESS"].to_s %>"
      rewards_distributor_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_REWARDS_DISTRIBUTOR_CONTRACT_ADDRESS"].to_s %>"
      realitio_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_REALITIO_ERC20_CONTRACT_ADDRESS"].to_s %>"
      achievements_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ACHIEVEMENTS_CONTRACT_ADDRESS"].to_s %>"
      voting_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_VOTING_CONTRACT_ADDRESS"].to_s %>"
      erc20_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ERC20_CONTRACT_ADDRESS"].to_s %>"
      arbitration_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ARBITRATION_CONTRACT_ADDRESS"].to_s %>"
      arbitration_proxy_contract_address: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ARBITRATION_PROXY_CONTRACT_ADDRESS"].to_s %>"
      arbitration_network_id: <%= ENV["ETHEREUM_NETWORK_#{network_id}_ARBITRATION_NETWORK_ID"].to_s %>
      image_url: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_IMAGE_URL"].to_s %>"
      burn_from_block: <%= ENV["ETHEREUM_NETWORK_#{network_id}_BURN_FROM_BLOCK"].to_i %>
      block_range: <%= ENV["ETHEREUM_NETWORK_#{network_id}_BLOCK_RANGE"].to_i %>
      tokens:
        <% ENV["ETHEREUM_NETWORK_#{network_id}_ERC20_CONTRACT_ADDRESSES"].to_s.split(',') do |contract_address| %>
          "<%= contract_address %>":
            name: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ERC20_#{contract_address}_NAME"].to_s %>"
            symbol: "<%= ENV["ETHEREUM_NETWORK_#{network_id}_ERC20_#{contract_address}_SYMBOL"].to_s %>"
        <% end %>
  <% end %>
  <% ENV["STATS_NETWORK_IDS"].to_s.split(',') do |network_id| %>
    stats_network_<%= network_id %>:
      bepro_api_url: <%= ENV["STATS_NETWORK_#{network_id}_BEPRO_API_URL"] %>
      prediction_market_contract_address: "<%= ENV["STATS_NETWORK_#{network_id}_PREDICTION_MARKET_CONTRACT_ADDRESS"].to_s %>"
      realitio_contract_address: "<%= ENV["STATS_NETWORK_#{network_id}_REALITIO_ERC20_CONTRACT_ADDRESS"].to_s %>"
  <% end %>
    market_list_url: <%= ENV['ETHEREUM_MARKET_LIST_URL'] %>
    network_ids: <%=
      ENV["ETHEREUM_NETWORK_IDS"].to_s.split(',').select do |network_id|
        ENV["ETHEREUM_NETWORK_#{network_id}_DISABLED"].to_s != 'true'
      end
    %>
    fantasy_enabled: <%= ENV["ETHEREUM_FANTASY_ENABLED"] == 'true' %>
    fantasy_advanced_mode: <%= ENV["ETHEREUM_FANTASY_ADVANCED_MODE"] == 'true' %>
    fantasy_tokens: <%= ENV["ETHEREUM_FANTASY_TOKENS"].to_s.split(',') %>
    stats_network_ids: <%= ENV["STATS_NETWORK_IDS"].to_s.split(',') %>
    cache_ttl_seconds: <%= ENV["ETHEREUM_CACHE_TTL"] %>
    voting_delta: <%= ENV["ETHEREUM_VOTING_DELTA"] || 3 %>
    blacklist: <%= ENV["ETHEREUM_BLACKLIST"].to_s.split(',') %>
    bundler_url: <%= ENV["ETHEREUM_BUNDLER_URL"] %>
    bundler_entry_point: "<%= ENV["ETHEREUM_BUNDLER_ENTRY_POINT"].to_s %>"
    bundler_pimlico_url: <%= ENV["ETHEREUM_BUNDLER_PIMLICO_URL"] %>
    bundler_pimlico_api_key: <%= ENV["ETHEREUM_BUNDLER_PIMLICO_API_KEY"] %>
    bundler_pimlico_network_ids: <%= ENV["ETHEREUM_BUNDLER_PIMLICO_NETWORK_IDS"].to_s.split(',').map(&:to_i) %>
    prediction_market_contract_version: <%= (ENV["ETHEREUM_PREDICTION_MARKET_CONTRACT_VERSION"] || 2).to_i %>
    token_amount_to_claim: <%= (ENV["ETHEREUM_TOKEN_AMOUNT_TO_CLAIM"]).to_i %>

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
