production:
  url: <%= ENV['ETHEREUM_URL'] %>
  contract_address: "<%= ENV['ETHEREUM_CONTRACT_ADDRESS'].to_s %>"

development:
   # local testnet
  url: 'http://localhost:8545'
  contract_address: '0x9b1f7F645351AF3631a656421eD2e40f2802E6c0'
  oracle_private_key: '0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d' # DO NOT USE THIS IN PRODUCTION

  # local testnet
  # url: <%= ENV['ETHEREUM_URL'] %>
  # contract_address: "<%= ENV['ETHEREUM_CONTRACT_ADDRESS'].to_s %>"
  # oracle_private_key: "<%= ENV['ETHEREUM_ORACLE_PRIVATE_KEY'].to_s %>" # DO NOT USE THIS IN PRODUCTION
