default: &default
  url: <%= ENV['ETHEREUM_URL'] %>
  network_id: <%= ENV['ETHEREUM_NETWORK_ID'] %>
  contract_address: "<%= ENV['ETHEREUM_CONTRACT_ADDRESS'].to_s %>"
  oracle_address: "<%= ENV['ETHEREUM_ORACLE_ADDRESS'].to_s %>"
  realitio_contract_address: "<%= ENV['ETHEREUM_REALITIO_ERC20_CONTRACT_ADDRESS'].to_s %>"
  erc20_contract_address: "<%= ENV['ETHEREUM_ERC20_CONTRACT_ADDRESS'].to_s %>"
  market_list_url: <%= ENV['ETHEREUM_MARKET_LIST_URL'] %>

production:
  <<: *default

staging:
  <<: *default
  oracle_private_key: "<%= ENV['ETHEREUM_ORACLE_PRIVATE_KEY'].to_s %>" # DO NOT USE THIS IN PRODUCTION

development:
  <<: *default
  oracle_private_key: "<%= ENV['ETHEREUM_ORACLE_PRIVATE_KEY'].to_s %>" # DO NOT USE THIS IN PRODUCTION
