# Be sure to restart your server when you modify this file.

default: &default
  <<: *default

  # ethereum
  ethereum_url: <%= ENV['ETHEREUM_URL'] %>
  ethereum_contract_address: "<%= ENV['ETHEREUM_CONTRACT_ADDRESS'].to_s %>"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
