default: &default
  <<: *default

  # listeners credentials
  spreadsheet_id: <%= ENV['WHITELIST_SPREADSHEET_ID'] %>
  spreadsheet_tab: <%= ENV['WHITELIST_SPREADSHEET_ID'] %>
  spreadsheet_range: <%= ENV['WHITELIST_SPREADSHEET_RANGE'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
